//mutations
const TEACH_MU_LOGIN = 'TEACH_MU_LOGIN'
const TEACH_MU_ADD = 'TEACH_MU_ADD'
const TEACH_MU_LIST = 'TEACH_MU_LIST'
const TEACH_MU_UPDATE = 'TEACH_MU_UPDATE'
const TEACH_MU_DELETE = 'TEACH_MU_DELETE'
const TEACH_MU_MODA = 'TEACH_MU_MODA'
//action
const TEACH_LOGIN = 'TEACH_LOGIN'
const TEACH_ADD = 'TEACH_ADD'
const TEACH_LIST = 'TEACH_LIST'
const TEACH_UPDATE = 'TEACH_UPDATE'
const TEACH_DELETE = 'TEACH_DELETE'
export {
  TEACH_LOGIN,
  TEACH_MU_LOGIN,
  TEACH_MU_ADD,
  TEACH_ADD,
  TEACH_LIST,
  TEACH_MU_LIST,
  TEACH_MU_UPDATE,
  TEACH_UPDATE,
  TEACH_DELETE,
  TEACH_MU_DELETE,
  TEACH_MU_MODA
}
